"""empty message

Revision ID: 27e4cda22d31
Revises: 41aff4e95fbc
Create Date: 2021-08-25 15:50:28.078048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e4cda22d31'
down_revision = '41aff4e95fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lineorder', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'lineorder', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lineorder', type_='foreignkey')
    op.drop_column('lineorder', 'product_id')
    # ### end Alembic commands ###
