"""empty message

Revision ID: 41aff4e95fbc
Revises: a0e23cf837d1
Create Date: 2021-08-25 15:48:41.150808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41aff4e95fbc'
down_revision = 'a0e23cf837d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineorder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('lineOrder')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineOrder',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"lineOrder_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='lineOrder_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='lineOrder_pkey')
    )
    op.drop_table('lineorder')
    # ### end Alembic commands ###
