"""empty message

Revision ID: 43936e4048c2
Revises: b36eda7bcdb7
Create Date: 2021-08-30 14:58:59.270166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43936e4048c2'
down_revision = 'b36eda7bcdb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('account', '_is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('account', 'payment_type',
               existing_type=postgresql.ENUM('Fiat', 'Paypal', 'Crypto', name='payment'),
               nullable=True)
    op.alter_column('account', 'review_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('product', 'media',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('product', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product', 'media',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('account', 'review_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('account', 'payment_type',
               existing_type=postgresql.ENUM('Fiat', 'Paypal', 'Crypto', name='payment'),
               nullable=False)
    op.alter_column('account', '_is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('account', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
