"""empty message

Revision ID: 7b5eb4ce8007
Revises: d3c6911e03d6
Create Date: 2021-09-03 07:45:57.195591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b5eb4ce8007'
down_revision = 'd3c6911e03d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('shopname', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'shopname')
    # ### end Alembic commands ###
