"""empty message

Revision ID: d3c6911e03d6
Revises: 
Create Date: 2021-08-26 15:02:29.648427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c6911e03d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password', sa.String(), nullable=False),
    sa.Column('_is_active', sa.Boolean(), nullable=True),
    sa.Column('payment_type', sa.Enum('Fiat', 'Paypal', 'Crypto', name='payment'), nullable=True),
    sa.Column('review_text', sa.String(), nullable=True),
    sa.Column('reviews_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviews_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('shipping_date', sa.DateTime(), nullable=False),
    sa.Column('shipping_fee', sa.Numeric(), nullable=False),
    sa.Column('bill_address', sa.String(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('media', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('category', sa.Enum('Clothing', 'Computers', 'Home & Garden', 'Sports', 'NFTs', 'Cellphones', 'Gaming', 'Movies, Books & Music', 'Appliances', 'TV, Audio & Cameras', 'Motorbikes', 'Other', name='categories'), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineorder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishlist',
    sa.Column('from_account', sa.Integer(), nullable=False),
    sa.Column('have_product', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_account'], ['account.id'], ),
    sa.ForeignKeyConstraint(['have_product'], ['product.id'], ),
    sa.PrimaryKeyConstraint('from_account', 'have_product')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist')
    op.drop_table('lineorder')
    op.drop_table('product')
    op.drop_table('order')
    op.drop_table('account')
    # ### end Alembic commands ###
